rios0rios0/pipelines

CHANGELOG.md
gitlab/golang/go-debian.yaml
gitlab/golang/stages/40-delivery/goreleaser.yaml
gitlab/golang/stages/50-deployment/debrelease.yaml

Tested to be working in a GitLab Golang repo.

feat(goreleaser): added the goreleaser pipelines

---

CHANGELOG.md
global/scripts/semgrep/run.sh

Allows it to be possible to override a Semgrep rule

feat(js): create option to override a semgrep rule

---

.github/PULL_REQUEST_TEMPLATE/default.md
CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

> ## 🚦 Quality checklist
> * [x]  Did you add the changes in the `CHANGELOG.md`?
> * [x]  Did you run all the code checks? (`go test`)
> * [x]  Are the tests passing?

feat(migrations): added step to create and delete firewall rule to run migrations

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

refactor(migrations): refactor firewall rules for migrations in delivery stage

---

CHANGELOG.md
azure-devops/javascript/stages/50-deployment/k8s.yaml

fix(js): changed javascript deployment to continue tasks with error

---

.github/workflows/go-binary.yaml
CHANGELOG.md
github/global/stages/40-delivery/binary/action.yaml
github/global/stages/40-delivery/release/action.yaml

feat(binary): added the binary release feature for GoLang pipelines

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

feat(seed): added a script into the golang delivery to seed the database using goose

---

CHANGELOG.md
gitlab/golang/stages/40-delivery/go-releaser.yaml

hotfix(golang): changed the GoLang pipeline to remove the redundant make command

---

CHANGELOG.md
global/scripts/gitleaks/.gitleaks.toml
global/scripts/gitleaks/run.sh

feat(gitleaks): added alibaba access key id regex to allowlist

---

CHANGELOG.md
gitlab/golang/stages/40-delivery/go-releaser.yaml

feat(goreleaser): added musl-tools to support building with musl

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

feat(golang): added task in delivery stage for variable replacement

---

CHANGELOG.md
gitlab/dotnet/abstracts/sdk.yaml
gitlab/dotnet/framework.yaml
gitlab/dotnet/stages/10-code-check/sdk.yaml
gitlab/dotnet/stages/20-security/csharp.yaml
gitlab/dotnet/stages/30-tests/msbuild.yaml
gitlab/dotnet/stages/35-management/sdk.yaml
gitlab/dotnet/stages/40-delivery/binary.yaml
gitlab/global/stages/35-management/abstracts.yaml
gitlab/golang/stages/35-management/go.yaml

feat(dotnet): added skeleton for .NET project pipelines with basic steps

---

CHANGELOG.md
gitlab/java/abstracts/gradle.yaml

feat(gradle): changed gradle version from 8.1 to 8.7

---

CHANGELOG.md
azure-devops/python/pdm-docker.yaml
azure-devops/python/stages/10-code-check/pdm.yaml
azure-devops/python/stages/20-security/pdm.yaml

The commit contains a template file to use via azure-pipelines, which will execute code-quality and code-security checks for python

feat(python-pipeline): added steps for performing code security-check and quality-check in azure-devops

---

CHANGELOG.md
azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/golang/stages/30-tests/go.yaml
azure-devops/golang/stages/40-delivery/arm.yaml

feat(golang): changed golang version in azure-devops from 1.20 to 1.22

---

CHANGELOG.md
azure-devops/global/stages/20-security/docker.yaml
azure-devops/golang/stages/40-delivery/arm.yaml
global/scripts/semgrep/run.sh

feat(security): added tasks to publish all security reports as Azure artifacts

---

CHANGELOG.md
gitlab/dotnet/stages/35-management/sdk.yaml

feat(dotnet-java): added java support on dotnet pipeline

---

CHANGELOG.md
gitlab/dotnet/stages/35-management/sdk.yaml

fix(dotnet-java): fixed wrong java package

---

CHANGELOG.md
azure-devops/python/pdm-docker.yaml
azure-devops/python/stages/40-delivery/docker.yaml

feat(python-pipeline): Added template to build and push python application via PDM to container registry

---

CHANGELOG.md
azure-devops/global/abstracts/clone-and-move-plugin-steps.yml

hotfix(node): node version upgrade from 16.20.0 to 18.19.0

---

CHANGELOG.md
gitlab/python/abstracts/pdm.yaml
gitlab/python/stages/30-tests/pdm.yaml

feat(pdm): install only production and test deps

---

CHANGELOG.md
gitlab/python/abstracts/pdm.yaml
gitlab/python/stages/40-delivery/pdm-library.yaml

fix(cache): pdm prod has it own cache now

---

CHANGELOG.md
azure-devops/javascript/stages/10-code-check/yarn.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml

fix(OS): changed the OSD version to 2.15.0 due to an upgrade request

---

CHANGELOG.md
gitlab/java/stages/20-security/gradle-application.yaml

feat(gradle): added a new env variable for java pipelines to avoid out-of-memory error

---

CHANGELOG.md
gitlab/javascript/stages/10-code-check/yarn.yaml

feat(js): remove code check after_script

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

feat(golang-delivery-script): fix script not returning non-zero exit code when there's an error

---

CHANGELOG.md
gitlab/golang/abstracts/go.yaml

feat(golang-version): changed golang version from 1.19 to 1.22

---

CHANGELOG.md

chore(bump): bumped version to 2.0.0

---

CHANGELOG.md
azure-devops/javascript/stages/10-code-check/yarn.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml

fix(OS): changed the OSD version to 2.16.0 due to an upgrade request

---

CHANGELOG.md
global/scripts/golang/test/run.sh

fix(golang-path): fixed golang root folder test to run the tests

---

CHANGELOG.md
global/scripts/golang/test/run.sh

fix(go-pipeline): fixed golang test coverage

---

CHANGELOG.md
global/scripts/golang/test/run.sh

fix(go-pipeline): fixed golang test argument passing errors

---

CHANGELOG.md
global/scripts/golang/test/run.sh

fix(go-pipeline): fixed golang test script directory search method

---

CHANGELOG.md
README.md
clone.sh

feat(add-clone-script): add clone script to be used in the project

---

CHANGELOG.md
global/scripts/golang/test/run.sh

feat(install-docker-goland-test): install docker when running goland test script

---

CHANGELOG.md
global/scripts/golangci-lint/.golangci.yml
global/scripts/golangci-lint/run.sh

Here are the changes on `.golangci.yml` from the original:
```diff
248c248
<     - godot # checks if comments end in a period
---
>     #- godot # checks if comments end in a period
313c313
<     #- err113 # [too strict] checks the errors handling expressions
---
>     - err113 # [too strict] checks the errors handling expressions
```

feat(go-pipeline): updated the golangci-lint pipeline to use a tweaked version of @maratori's config

---

CHANGELOG.md
global/scripts/golangci-lint/.golangci.yml

fix(go-pipeline): added two missing linters

---

.github/workflows/go.yaml
CHANGELOG.md
azure-devops/golang/stages/10-code-check/go.yaml
gitlab/global/abstracts/scripts-repo-debian.yaml

fix(go-pipeline): added sudo to fix apt-get insufficient permission error

---

.github/workflows/python.yaml
CHANGELOG.md

feat(github): run steps on python-pdm container

---

CHANGELOG.md
gitlab/golang/stages/30-tests/go.yaml

feat(go-pipeline): added a build step for gitlab golang pipeline

---

CHANGELOG.md
github/global/stages/20-security/docker-gitleaks/action.yaml
github/global/stages/20-security/docker-horusec/action.yaml
github/global/stages/20-security/docker-semgrep/action.yaml
global/scripts/horusec/default.json

ci(sast): added artifact upload for SAST pipelines

---

github/global/stages/20-security/docker-gitleaks/action.yaml
github/global/stages/20-security/docker-horusec/action.yaml
github/global/stages/20-security/docker-semgrep/action.yaml

ci(sast): updated SAST pipelines' step names

---

CHANGELOG.md
global/scripts/golang/test/run.sh

feat(tests): separate integration test to test once per time

---

CHANGELOG.md
gitlab/golang/abstracts/go.yaml

chore(bump): bump go version to gitlab

---

CHANGELOG.md
azure-devops/javascript/stages/10-code-check/yarn.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml

feat(OS): changed the OSD version to 2.17.0 due to an upgrade request

---

CHANGELOG.md
azure-devops/global/abstracts/clone-and-move-opensearch-dashboards.yaml
azure-devops/global/abstracts/execute-command-opensearch-dashboards.yaml
azure-devops/global/abstracts/replace-environment-variables.yaml
azure-devops/global/abstracts/run-test-e2e.yaml
azure-devops/javascript/stages/10-code-check/yarn.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml
azure-devops/javascript/stages/50-deployment/k8s.yaml

feat(e2e): added command to run `e2e` tests

---

CHANGELOG.md
global/scripts/gitleaks/.gitleaks.toml

feat(gitleaks-rules): added gitleaks rules specific to azure sensitive values

---

CHANGELOG.md
global/scripts/gitleaks/.gitleaks.toml

rollback(gitleaks-rules): rollback gitleaks confidential uuid

---

CHANGELOG.md
gitlab/dotnet/abstracts/framework.yaml
gitlab/dotnet/abstracts/powershell.yaml

feat(cs-pipeline): run CSharp tests in Debug configuration

---

.github/workflows/python.yaml
CHANGELOG.md
github/global/stages/20-security/docker-gitleaks/action.yaml
github/global/stages/20-security/docker-horusec/action.yaml
github/global/stages/20-security/docker-semgrep/action.yaml
global/containers/python.3.10-pdm-bullseye/Dockerfile

ci(github): fixed Python pipeline execution

---

CHANGELOG.md
azure-devops/global/abstracts/run-test-e2e.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml

fix(e2e): added command to run rename_vars.sh file

---

CHANGELOG.md
azure-devops/global/abstracts/clone-and-move-opensearch-dashboards.yaml
azure-devops/global/abstracts/execute-command-opensearch-dashboards.yaml
azure-devops/global/abstracts/replace-environment-variables.yaml
azure-devops/global/abstracts/run-test-e2e.yaml
azure-devops/global/stages/20-security/docker.yaml
azure-devops/global/stages/35-management/dependency-track.yaml
azure-devops/global/stages/35-management/sonarqube.yaml
azure-devops/golang/go-arm.yaml
azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/golang/stages/20-security/go.yaml
azure-devops/golang/stages/30-tests/go.yaml
azure-devops/golang/stages/35-management/go.yaml
azure-devops/golang/stages/40-delivery/arm.yaml
azure-devops/javascript/stages/20-security/yarn.yaml
azure-devops/javascript/stages/35-management/npm-yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml
azure-devops/javascript/stages/50-deployment/k8s.yaml
azure-devops/javascript/yarn-docker.yaml
azure-devops/python/stages/20-security/pdm.yaml

feat(management): added management step for Azure DevOps environment using JS and GoLang

---

CHANGELOG.md
gitlab/python/stages/35-management/pdm.yaml

fix(python-managment): fix sonarqube step to adjust the script for non debian image

fix(python-management): fix sonarqube step to adjust the script for non-debian image

---

CHANGELOG.md
azure-devops/global/stages/35-management/sonarqube.yaml
azure-devops/golang/stages/30-tests/go.yaml

fix(sonarqube): added a step to publish the code coverage

---

CHANGELOG.md
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/35-management/yarn.yaml

fix(sonarqube): fixed an error to execute the sonarqube

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

feat(azdevops-golang-delivery-caching): create cache to avoid unnecessary processing

---

CHANGELOG.md
azure-devops/global/abstracts/run-test-e2e.yaml

fix(test_artifact): fixed artifact generation for `e2e` tests

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

fix(azdevops-delivery-gobuild): create bin directory on build step

---

CHANGELOG.md
global/scripts/golang/test/run.sh

fix(golang-test): add more directories for testing

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

fix(azure-migrations): changed the pipeline to run the migrations and seeders in a different tasks

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

fix(az-devops-delivery): change to get only the last deployed function

---

CHANGELOG.md
azure-devops/javascript/stages/30-tests/yarn.yaml

fix(pool): changed `e2e` test job to receive a different pool

---

CHANGELOG.md
azure-devops/global/abstracts/execute-command-opensearch-dashboards.yaml
azure-devops/golang/stages/40-delivery/arm.yaml

feat(azdevops-js-cache): create cache for open search command template

---

azure-devops/global/abstracts/clone-and-move-opensearch-dashboards.yaml
azure-devops/global/abstracts/execute-command-opensearch-dashboards.yaml
azure-devops/global/abstracts/replace-environment-variables.yaml
azure-devops/global/abstracts/run-test-e2e.yaml
azure-devops/global/stages/20-security/docker.yaml
azure-devops/global/stages/35-management/sonarqube.yaml
azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/golang/stages/30-tests/go.yaml
azure-devops/golang/stages/35-management/go.yaml
azure-devops/golang/stages/40-delivery/arm.yaml
azure-devops/javascript/stages/35-management/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml
azure-devops/javascript/stages/50-deployment/k8s.yaml
azure-devops/python/stages/10-code-check/pdm.yaml
azure-devops/python/stages/40-delivery/docker.yaml

fix(minor): corrected quotes and positioning of each job/step for Azure DevOps

---

CHANGELOG.md
azure-devops/global/abstracts/run-test-e2e.yaml
azure-devops/golang/stages/30-tests/go.yaml
azure-devops/golang/stages/40-delivery/arm.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml

feat(azdevops-js-caching): create cache for javascript stages

---

CHANGELOG.md
azure-devops/javascript/stages/10-code-check/yarn.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml

feat(os): changed the OSD version to 2.18.0 due to an upgrade request

---

CHANGELOG.md
azure-devops/javascript/abstracts/execute-command-opensearch-dashboards.yaml

fix(azdevops-js): change inconsistent task version

---

CHANGELOG.md
azure-devops/global/stages/35-management/sonarqube.yaml
azure-devops/global/stages/40-delivery/release.yaml
azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/golang/stages/20-security/go.yaml
azure-devops/golang/stages/30-tests/go.yaml
azure-devops/golang/stages/35-management/go.yaml
azure-devops/golang/stages/40-delivery/arm.yaml
azure-devops/javascript/abstracts/execute-command-opensearch-dashboards.yaml
azure-devops/javascript/abstracts/run-test-e2e.yaml
azure-devops/javascript/stages/10-code-check/yarn.yaml
azure-devops/javascript/stages/20-security/yarn.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/35-management/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml
azure-devops/javascript/stages/50-deployment/k8s.yaml
azure-devops/python/stages/10-code-check/pdm.yaml
azure-devops/python/stages/20-security/pdm.yaml
azure-devops/python/stages/40-delivery/docker.yaml

fix(consistency): changed all display names and conditions to obey a certain position

---

CHANGELOG.md
azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/golang/stages/30-tests/go.yaml
azure-devops/golang/stages/35-management/go.yaml
azure-devops/golang/stages/40-delivery/arm.yaml
azure-devops/javascript/abstracts/execute-command-opensearch-dashboards.yaml
azure-devops/javascript/abstracts/run-test-e2e.yaml
azure-devops/javascript/stages/35-management/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml
global/scripts/golang/test/run.sh

fix(go-test-cache): corrected the cache in Go test script

---

CHANGELOG.md
azure-devops/global/stages/35-management/dependency-track.yaml

fix(dependency-track): corrected Dependency Track to avoid creating many of the same project

---

CHANGELOG.md
gitlab/golang/stages/35-management/go.yaml

fix(go-pipeline): fixed incorrect string concatenations

---

azure-devops/global/stages/35-management/dependency-track.yaml
azure-devops/golang/stages/35-management/go.yaml
gitlab/golang/stages/35-management/go.yaml

fix(env): corrected environment variables being handled as commands

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/arm.yaml

fix(azdevops-golang-delivery): add a goose db version table hash for the migrations and seeders caches

---

CHANGELOG.md
azure-devops/javascript/abstracts/run-test-e2e.yaml

fix(token_helper_path): fixed path to `token_helpers.ts` file in `test_e2e` job

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/dynamic-go-arm.yaml
azure-devops/golang/stages/40-delivery/fixed-go-arm.yaml

fix(unused-parameter): removed unnecessary parameters

---

CHANGELOG.md
azure-devops/global/stages/35-management/sonarqube.yaml
azure-devops/golang/stages/35-management/go.yaml
gitlab/golang/stages/35-management/go.yaml

fix(sonarqube): corrected SonarQube to detect blame information and tags

---

CHANGELOG.md
azure-devops/global/stages/35-management/sonarqube.yaml
azure-devops/golang/stages/35-management/go.yaml
azure-devops/javascript/stages/35-management/yarn.yaml
gitlab/global/stages/35-management/abstracts.yaml
gitlab/golang/stages/35-management/go.yaml
global/scripts/golang/cyclonedx/run.sh
global/scripts/golang/test/run.sh
global/scripts/sonarqube/run.sh

fix(sonarqube): removed duplicated code of SonarQube and DependencyTrack for GitLab and Azure DevOps

---

CHANGELOG.md
azure-devops/global/stages/20-security/docker.yaml
azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/golang/stages/30-tests/go.yaml

fix(gitleaks): changed inside Azure DevOps to clone full repository instead of just shallow clone

---

CHANGELOG.md
azure-devops/global/abstracts/database.yaml
azure-devops/global/abstracts/deploy-az-function.yaml
azure-devops/global/stages/50-deployment/dynamic.yaml
azure-devops/global/stages/50-deployment/fixed.yaml
azure-devops/golang/dynamic-go-arm.yaml
azure-devops/golang/fixed-go-arm.yaml
azure-devops/golang/stages/40-delivery/arm-dynamic.yaml
azure-devops/golang/stages/40-delivery/arm-fixed.yaml

fix(distributed-deploy): changed the distributed deploy to create the artifacts instead of deploying the Azure function

---

azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/golang/stages/30-tests/go.yaml
azure-devops/golang/stages/35-management/go.yaml
azure-devops/golang/stages/40-delivery/arm-dynamic.yaml
azure-devops/golang/stages/40-delivery/arm-fixed.yaml
gitlab/golang/stages/35-management/go.yaml
global/scripts/golang/init/run.sh

fix(duplicated-code): removed duplicated code from GoLang pipelines

---

CHANGELOG.md
azure-devops/terraform/stages/10-code-check/terra.yaml
azure-devops/terraform/terra.yaml

feat(terraform): added a new pipeline in Azure DevOps for Terraform

---

CHANGELOG.md
azure-devops/dotnet/abstracts/core-sdk6.x.yaml
azure-devops/dotnet/core.yaml
azure-devops/dotnet/stages/10-code-check/core.yaml
azure-devops/dotnet/stages/20-security/csharp.yaml
azure-devops/dotnet/stages/35-management/core.yaml
azure-devops/golang/stages/10-code-check/go.yaml
azure-devops/terraform/stages/10-code-check/terra.yaml
azure-devops/terraform/stages/35-management/terra.yaml

feat(dotnet): added a new pipeline in Azure DevOps for .NET Core (C#)

---

CHANGELOG.md
global/scripts/golang/cyclonedx/run.sh

fix(cyclonedx): corrected wrong usage of CycloneDX library for GoLang

---

CHANGELOG.md
README.md
azure-devops/dotnet/abstracts/core-sdk6.x.yaml
azure-devops/dotnet/core.yaml
azure-devops/dotnet/stages/10-code-check/core.yaml
azure-devops/dotnet/stages/30-tests/core.yaml
azure-devops/dotnet/stages/35-management/core.yaml

fix(dotnet): corrected miss-used template files for .NET in Azure DevOps pipelines

---

CHANGELOG.md
azure-devops/golang/container-deployment.yaml
azure-devops/golang/stages/40-delivery/docker.yaml

feat(image-deployment): added stage to build and deploy az devops hosted golang images

---

CHANGELOG.md
azure-devops/golang/stages/40-delivery/docker.yaml

refactor(golang-docker): change image tag and add default golang template

---

CHANGELOG.md
azure-devops/golang/abstracts/test.yaml
azure-devops/golang/acr-container-deployment.yaml
azure-devops/golang/stages/30-tests/acr.yaml

feat(golang-test-acr): add another stage to the GoLang pipeline to log into ACR before running tests

---

CHANGELOG.md
azure-devops/golang/container-deployment.yaml
azure-devops/golang/stages/40-delivery/docker.yaml
azure-devops/golang/stages/50-deployment/arm-container.yaml

feat(arm-container): added steps to deploy a container into Azure via the ARM

---

CHANGELOG.md
azure-devops/global/abstracts/docker.yaml
azure-devops/golang/stages/40-delivery/docker.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml

fix(golang-docker): changed `docker.yaml` Golang delivery stage to handle image tag name gracefully

---

CHANGELOG.md
azure-devops/javascript/abstracts/run-test-e2e.yaml

feat(e2e): added messages to show application states in the `test_e2e` job

---

CHANGELOG.md
azure-devops/global/abstracts/docker.yaml
azure-devops/javascript/stages/50-deployment/k8s.yaml

fix(azdevops-docker): fix docker delivery template and JS delivery stage

---

CHANGELOG.md
azure-devops/javascript/abstracts/clone-and-move-opensearch-dashboards.yaml
azure-devops/javascript/abstracts/corepack-node18.19.0-no-cache.yaml
azure-devops/javascript/abstracts/corepack-node18.19.0.yaml

Fixed to the correct PATH of node modules.

fix(node-cache): fixed cache error of azure pipeline for javascript

---

CHANGELOG.md
azure-devops/javascript/abstracts/execute-command-opensearch-dashboards.yaml

fix(yarn-cache): changed yarn cache key to use the OSD and

---

CHANGELOG.md
azure-devops/global/stages/40-delivery/docker.yaml
azure-devops/golang/go-arm-docker.yaml
azure-devops/golang/stages/40-delivery/docker.yaml

fix(go-docker): introduce new parameters to configure docker build

---

CHANGELOG.md
azure-devops/global/stages/50-deployment/fixed.yaml
azure-devops/golang/go-arm-azfunction.yaml
azure-devops/golang/stages/50-deployment/arm-fixed.yaml

feat(optional-params-az-func): added a new optional parameter to run in resource group

feat(optional-params-az-func): added a new optional parameter to run in resource group

---

CHANGELOG.md
azure-devops/javascript/abstracts/run-test-e2e.yaml

fix(kill-ports): fixed script that kills processes created by OSD

---

CHANGELOG.md
azure-devops/global/stages/50-deployment/arm-parameters.yaml
azure-devops/golang/go-arm-docker.yaml
azure-devops/golang/stages/50-deployment/arm-container.yaml

…ry variables into ARM parameters

feat(arm-parameters): created template to transform library variables into ARM parameters

---

CHANGELOG.md
azure-devops/global/stages/50-deployment/database.yaml

these files are used for the cache key, but some of them could be inside other subfolders, than occurs an error to find them.

fix(seeders-cache): fixed the pattern to find seeder and migration files

---

CHANGELOG.md
global/scripts/golangci-lint/.golangci.yml

fix(golangci-lint): upgraded the @maratori's configuration to v1.64.7

---

CHANGELOG.md
azure-devops/global/stages/50-deployment/database.yaml
azure-devops/global/stages/50-deployment/deploy-az-function.yaml
azure-devops/global/stages/50-deployment/dynamic.yaml
azure-devops/global/stages/50-deployment/fixed.yaml
azure-devops/golang/stages/40-delivery/arm-dynamic.yaml
azure-devops/golang/stages/40-delivery/arm-fixed.yaml
azure-devops/golang/stages/50-deployment/arm-fixed.yaml

fix(db-pipeline): changed PIPELINE_FIREWALL_NAME to be a job variable

---

CHANGELOG.md
azure-devops/global/stages/50-deployment/database.yaml
azure-devops/java/abstracts/code-check.yaml
azure-devops/java/abstracts/gradle.yaml
azure-devops/java/kotlin-gradle.yaml
azure-devops/java/stages/10-code-check/java.yaml
azure-devops/java/stages/10-code-check/kotlin.yaml
azure-devops/java/stages/20-security/java.yaml
azure-devops/java/stages/30-tests/gradle.yaml
azure-devops/java/stages/40-delivery/gradle.yaml

feat(az-devops-java): create java stages to azure devops

---

CHANGELOG.md
azure-devops/java/abstracts/code-check.yaml
azure-devops/java/abstracts/gradle.yaml
azure-devops/java/kotlin-gradle.yaml
azure-devops/java/stages/10-code-check/java.yaml
azure-devops/java/stages/10-code-check/kotlin.yaml
azure-devops/java/stages/30-tests/gradle.yaml
azure-devops/java/stages/40-delivery/gradle.yaml

fix(az-devops-java): fix gradle properties

---

CHANGELOG.md
azure-devops/javascript/stages/50-deployment/k8s.yaml

feat(deploy-app): changed the way to get the k8s manifest in javascript pipeline

---

CHANGELOG.md
azure-devops/java/abstracts/code-check.yaml
azure-devops/java/abstracts/gradle.yaml
azure-devops/java/stages/10-code-check/kotlin.yaml
azure-devops/java/stages/40-delivery/gradle.yaml
global/configs/java/checkstyle/google-checkstyle10.12.4.xml

feat(java-checkstyle): add checkstyle config

---

CHANGELOG.md
global/scripts/golangci-lint/.golangci.yml

fix(golangci-lint): updated the golangci-lint config file

---

global/scripts/golangci-lint/.golangci.yml

refactor(golangci-lint): new golangci lint config file

---

CHANGELOG.md
azure-devops/global/stages/40-delivery/docker.yaml
azure-devops/golang/stages/50-deployment/arm-container.yaml
azure-devops/python/stages/40-delivery/docker.yaml

fix(dynamic-tags): fixed dynamic tags for prod and dev environment

---

CHANGELOG.md
azure-devops/global/stages/50-deployment/database.yaml

refactor(golang-database): remove cache from database migration template

---

CHANGELOG.md
azure-devops/javascript/abstracts/clone-and-move-opensearch-dashboards.yaml
azure-devops/javascript/abstracts/corepack-node20.18.3-no-cache.yaml
azure-devops/javascript/abstracts/corepack-node20.18.3.yaml
azure-devops/javascript/abstracts/execute-command-opensearch-dashboards.yaml
azure-devops/javascript/stages/10-code-check/yarn.yaml
azure-devops/javascript/stages/30-tests/yarn.yaml
azure-devops/javascript/stages/35-management/yarn.yaml
azure-devops/javascript/stages/40-delivery/docker.yaml

feat(OSD): changed the OSD version to  due to an upgrade request

---

azure-devops/global/stages/40-delivery/docker.yaml
azure-devops/javascript/stages/40-delivery/steps/delivery.yaml

feat(docker-args): accept docker arguments in delivery step
